/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:Bussola[MAX_PLAYERS][1];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	Bussola[playerid][0] = CreatePlayerTextDraw(playerid, 322.000000, 434.000000, "120");
	PlayerTextDrawFont(playerid, Bussola[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, Bussola[playerid][0], 0.324999, 1.249999);
	PlayerTextDrawTextSize(playerid, Bussola[playerid][0], 343.500000, 11.000000);
	PlayerTextDrawSetOutline(playerid, Bussola[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, Bussola[playerid][0], 1);
	PlayerTextDrawAlignment(playerid, Bussola[playerid][0], 2);
	PlayerTextDrawColor(playerid, Bussola[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, Bussola[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, Bussola[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, Bussola[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, Bussola[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, Bussola[playerid][0], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, Bussola[playerid][0]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, Bussola[playerid][0]);
		return 1;
	}
	return 0;
}
