/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:barrainfo[MAX_PLAYERS][8];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	barrainfo[playerid][0] = CreatePlayerTextDraw(playerid, 321.000000, 122.000000, "_");
	PlayerTextDrawFont(playerid, barrainfo[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][0], 0.558332, 3.300003);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][0], 298.500000, 235.000000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][0], 2);
	PlayerTextDrawColour(playerid, barrainfo[playerid][0], -1);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][0], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][0], 135);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][0], 0);

	barrainfo[playerid][1] = CreatePlayerTextDraw(playerid, 221.000000, 121.000000, "!");
	PlayerTextDrawFont(playerid, barrainfo[playerid][1], 0);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][1], 0.600000, 2.999999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][1], 227.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][1], 1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][1], -16776961);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][1], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][1], 1);

	barrainfo[playerid][2] = CreatePlayerTextDraw(playerid, 433.000000, 113.000000, "X");
	PlayerTextDrawFont(playerid, barrainfo[playerid][2], 1);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][2], 0.516664, 1.649999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][2], 445.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][2], 1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][2], -65281);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][2], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][2], 1);

	barrainfo[playerid][3] = CreatePlayerTextDraw(playerid, 248.000000, 125.000000, "HUD:radar_hostpital");
	PlayerTextDrawFont(playerid, barrainfo[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][3], 0.600000, 2.999999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][3], 16.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][3], 1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][3], -1);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][3], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][3], 1);

	barrainfo[playerid][4] = CreatePlayerTextDraw(playerid, 283.000000, 125.000000, "HUD:radar_ammugun");
	PlayerTextDrawFont(playerid, barrainfo[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][4], 0.600000, 2.999999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][4], 16.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][4], 1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][4], -1);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][4], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][4], 1);

	barrainfo[playerid][5] = CreatePlayerTextDraw(playerid, 404.000000, 125.000000, "HUD:radar_ryder");
	PlayerTextDrawFont(playerid, barrainfo[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][5], 0.600000, 2.999999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][5], 16.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][5], 1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][5], -1);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][5], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][5], 1);

	barrainfo[playerid][6] = CreatePlayerTextDraw(playerid, 315.000000, 125.000000, "ld_beat:up");
	PlayerTextDrawFont(playerid, barrainfo[playerid][6],TEXT_DRAW_FONT: 4);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][6], 0.600000, 2.999999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][6], 16.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][6], TEXT_DRAW_ALIGN: 1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][6], -1);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][6], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][6], true);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][6], true);

	barrainfo[playerid][7] = CreatePlayerTextDraw(playerid, 346.000000, 125.000000, "ld_beat:down");
	PlayerTextDrawFont(playerid, barrainfo[playerid][7], TEXT_DRAW_FONT:4);
	PlayerTextDrawLetterSize(playerid, barrainfo[playerid][7], 0.600000, 2.999999);
	PlayerTextDrawTextSize(playerid, barrainfo[playerid][7], 16.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, barrainfo[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, barrainfo[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, barrainfo[playerid][7], TEXT_DRAW_ALIGN:1);
	PlayerTextDrawColour(playerid, barrainfo[playerid][7], -1);
	PlayerTextDrawBackgroundColour(playerid, barrainfo[playerid][7], 255);
	PlayerTextDrawBoxColour(playerid, barrainfo[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, barrainfo[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, barrainfo[playerid][7], true);
	PlayerTextDrawSetSelectable(playerid, barrainfo[playerid][7], true);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][0]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][1]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][2]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][3]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][4]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][5]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][6]);
	PlayerTextDrawDestroy(playerid, barrainfo[playerid][7]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, barrainfo[playerid][0]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][1]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][2]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][3]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][4]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][5]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][6]);
		PlayerTextDrawShow(playerid, barrainfo[playerid][7]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
